name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Asisya.Catalog.sln

      - name: Build
        run: dotnet build Asisya.Catalog.sln --no-restore -c Release

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Asisya.Catalog.sln

      - name: Test
        run: dotnet test Asisya.Catalog.sln --configuration Release --verbosity normal
